version: '3'

services:
  ale_blog_app:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ale_blog_app
    container_name: ale_blog_app_container
    working_dir: /my_blog
    volumes:
      - database_local:/my_blog/database
      - .:/my_blog
    ports:
      - "8000:8000"
    command: /start.sh



