version: '3'
#version 代表 docker-compose.yml 的版本

services:
  blog_app_pro:
    image: ale_app_pro
    container_name: blog_app_pro
    restart: always
    command: bash ./compose/production/django/start.sh
    build:
      context: .
      # '点'代表当前目录
      dockerfile: ./compose/production/django/Dockerfile
    volumes:
      - ./media:/my_blog/media
      - ./static:/my_blog/static
      - ./accstat:/my_blog/accstat
      - ./blog:/my_blog/blog
      - ./blogproject:/my_blog/blogproject
      - ./comments:/my_blog/comments
      - ./templates:/my_blog/templates
      - ./userprofile:/my_blog/userprofile
    # "static" 表示宿主机的static目录，":" 为分隔符，"/app/static" 表示容器中的目录。
    #即宿主机目录和容器目录建立连通关系，宿主机目录的 Django 代码更新时，容器中的目录中的代码也相应的更新了。
    ports:
      - "8000:8000"
    links:
      - blog_mysql_pro:blog_mysql_pro
    depends_on:
      - blog_mysql_pro

  blog_nginx_pro:
    image: ale_nginx_pro
    container_name: blog_nginx_pro
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
#    volumes:
#      - static:/app/static
    ports:
      - "80:80"
      - "443:443"
    links:
      - blog_app_pro
    depends_on:
      - blog_app_pro


  blog_mysql_pro:
    image: ale_mysql_pro
    container_name: blog_mysql_pro
    restart: always
    build:
      contant: .
      dockerfile: ./compose/production/mysql/Dockerfile
    volumes:
      - ./production/mysql:/opt     #脚本目录
    ports:
      - "13306:13306"
    environment:
      - MYSQL_ROOT_PASSWORD=Wl410078368/*
#      - MYSQL_DATABASE=ale_blog
