# Generated by Django 2.2.3 on 2019-12-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20191221_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='名字'),
        ),
    ]
